import { 
    FaYoutube,
    FaInstagram,
    FaTiktok,
    FaLinkedin,
    FaTwitter,
    FaLinkedinIn,
 } from "react-icons/fa";

export const contentTemplates = [
    {
    name: "Youtube Video Description",
    desc: "An AI tool that generates youtube video description",
    category: "Youtube",
    icon: FaYoutube,
    aiPrompt: "Give me youtube video description ideas based on given video description outline and title and give me in rich text editor format",
    slug: 'youtube-description',
    form: [
        { label: "Youtube Video Description Title", 
        field: 'input', 
        name:'title',
        required: true,
    },
    { label: "Enter Youtube Video Description Outline", 
        field: 'textarea', 
        name:'outline',
        required: true,
      },
     ],
    },
    {
        name: "Youtube Video Idea",
        desc: "An AI tool that generates youtube video idea",
        category: "Youtube",
        icon: FaYoutube,
        aiPrompt: "Give me youtube video idea on given video niche & outline topic",
        slug: 'generate-youtube-video-idea',
        form: [
            { label: "Enter your video niche", 
            field: 'input', 
            name:'niche',
            required: true,
        },
        { label: "Enter Video Outline", 
            field: 'textarea', 
            name:'outline',
          },
         ],
        },
        {
            name: "Instagram Hashtags",
            desc: "An AI tool that generates Instagram hastags based on your posts",
            category: "Instagram",
            icon: FaInstagram,
            aiPrompt: "Give me some good examples of instagram hastags on given video niche & outline topic",
            slug: 'generate-instagram-hastags',
            form: [
                { label: "Enter your post niche", 
                field: 'input', 
                name:'niche',
                required: true,
            },
            { label: "Enter Video Outline", 
                field: 'textarea', 
                name:'outline',
              },
             ],
            },
            {
                name: "Tiktok Hashtags",
                desc: "An AI tool that generates Tiktok topic idea based on your posts",
                category: "Tiktok",
                icon: FaTiktok,
                aiPrompt: "Give me some good examples of Tiktok hastags on given niche & outline topic",
                slug: 'generate-tiktok-hastags',
                form: [
                    { label: "Enter your post niche", 
                    field: 'input', 
                    name:'niche',
                    required: true,
                },
                { label: "Enter Video Outline", 
                    field: 'textarea', 
                    name:'outline',
                  },
                 ],
                },
                {
                    name: "LinkedIn Post",
                    desc: "An AI tool that generates LinkedIn topic idea based on your posts",
                    category: "LinkedIn",
                    icon: FaLinkedin,
                    aiPrompt: "Give me some good examples of LinkedIn Post Idea on given niche & outline topic",
                    slug: 'generate-linkedin-hastags',
                    form: [
                        { label: "Enter your post niche", 
                        field: 'input', 
                        name:'niche',
                        required: true,
                    },
                    { label: "Enter Video Outline", 
                        field: 'textarea', 
                        name:'outline',
                      },
                     ],
                    },
                    {
                        name: "Tweet",
                        desc: "An AI tool that generates Tweet Post ideas based on your posts nivhe & outline topic",
                        category: "Tweet",
                        icon: FaTwitter,
                        aiPrompt: "Give me 280 characters of tweet examples on given niche & outline topic",
                        slug: 'generate-tweet-post',
                        form: [
                            { label: "Enter your tweet niche", 
                            field: 'input', 
                            name:'niche',
                            required: true,
                        },
                        { label: "Enter Video Outline", 
                            field: 'textarea', 
                            name:'outline',
                          },
                         ],
                        },

];